version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - redundancy-network
  web1:
    container_name: apache_php1
    build: ./docker/web
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./public_html:/var/www/html
      - ./docker/logs:/var/log/httpd
    depends_on:
      - master
      - slave
    networks:
      - redundancy-network
  web2:
    container_name: apache_php2
    build: ./docker/web
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./docker/logs:/var/log/httpd
    depends_on:
      - master
      - slave
    networks:
      - redundancy-network
  mysql_master:
    container_name: mysql_master
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/master/:/conf
      - ./db/setup.sh:/usr/local/bin/setup.sh
      - master_log:/var/log/mysql/
      - master_db:/var/lib/mysql
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'master'
    networks:
      - redundancy-network

  phpmyadmin1:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_master
      - PMA_USER=root
      - PMA_PASSWORD=master
    links:
      - mysql_master
    volumes:
      - /sessions
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - redundancy-network
volumes:
  master_db: {}
  master_log: {}
  slave_db: {}
  slave_log: {}

networks:
  redundancy-network:
    driver: bridge